### ISSUE TITLE
Did not work in addon used in an in repo engine

### ISSUE THREAD

**Issue by Gaurav0** [mansona/ember-get-config#18]
Hi,

I tried to use this in an addon that was used within an in repo engine. It returned the config:environment in that engine rather than the entire application.

The following code worked instead:

```js
const store = getOwner(this).lookup('service:store');
const ENV = getOwner(store).resolveRegistration('config:environment');
return ENV.featureFlags[params[0]];
```

I picked the ember-data store service because it was imported to the app and then shared with the engine. However, this cannot be guaranteed in general, so if anyone has any other ideas, let me know.

**Comment by mansona** [comment]
This is a very old issue and a lot of problems have been fixed recently 👍
