### ISSUE TITLE
Release v1.0?

### ISSUE THREAD

**Issue by jrjohnson** [mansona/ember-get-config#21]
This addon has been stable for a long time and seems ready for a 1.0 release, it would be a huge help to addons using this package to have a 1.0 release as declaring `^1.0.0` in `package.json` wouldn't require an update when a new minor version is released. On the other hand the 0.3.0 release this week is going to require a lot of churn to ship across the ember ecosystem.

Thanks for a great addon!

**Comment by jrjohnson** [comment]
@mansona it looks like you bumped a release today, just wanted to ping you on this. 0.4.0 is going to once again cause a bunch of churn for dependency-lint enabled apps while addons get caught up. 1.0.0 would be much appreciated.

**Comment by mansona** [comment]
now that #29 is merged I have released v1.0.0 🎉

**Comment by jrjohnson** [comment]
Thanks for pushing this over the line!
