### ISSUE TITLE
Absolute path to package is presented in the build output assets 

### ISSUE THREAD

**Issue by stevcooo** [mansona/ember-get-config#51]
**Describe the bug**
When you install [`ember-get-config": "^2.1.1"`](https://github.com/mansona/ember-get-config/releases/tag/v2.1.1) and do an `ember build --prod`, the output file `vendor....js` in `dist` folder contains the absolute path, `C:\\Source\\Lab\\fa-test\\node_modules\\ember-get-config` in my case . I've noticed that this has been the case since [1.0.0 version](https://github.com/mansona/ember-get-config/releases/tag/v1.0.0), previously it wasn't the case. I've tried with the 0.5.0 version and it doesn't include the absolute path in the output file.

**Reproducible test case**
Here I've created a repo where the issue can be reproduced easily [fa-test](https://github.com/stevcooo/fa-test).  If you want you can directly examine the [vendor file](https://github.com/stevcooo/fa-test/blob/master/dist/assets/vendor-1d34ecfc5e3d346ecac926c16af3ad84.js#L5031).   
Or get the repo, and do  `npm install` and examine `vendor...js` file in `dist` folder, you should see an absolute path to one of the packages in your local machine.

**Expected behavior**
We want deterministic builds that are absolute-path invariant (i.e. the build output shouldn't depend on the machine or the project's location in the file system). Sometimes we build on our local machine, but sometimes the build is done in some agent (CI/CD Azure for example). We want build outputs to be identical no matter the machine they are built on.
This is a regression issue, it wasn't presented earlier [`v0.5.0`](https://github.com/mansona/ember-get-config/releases/tag/v0.5.0) version that we used.

**Desktop (please complete the following information):**
 - Browser: Chrome
 - Version: 104.0.5112.81 (Official Build) (64-bit)

**Additional context**
Please check the [ReadMe](https://github.com/stevcooo/fa-test#readme) file for more instructions about this issue.

**Comment by bertdeblock** [comment]
I _think_ `@embroider/macros` is responsible for that value and not `ember-get-config` itself.

**Comment by bertdeblock** [comment]
Looks like this can be closed now?

**Comment by stevcooo** [comment]
> Looks like this can be closed now?

I'm not sure when is the release planned, but yes, looks like this can be closed now.

**Comment by stevcooo** [comment]
We can close this now. This issue is now resolved since it was originally caused by @embroider/macros, just use @embroider/macros >=1.9.0.
https://github.com/embroider-build/embroider/releases/tag/release-2022-10-06.0
